cicd: deploy to development added to openshift

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,8 +4,6 @@ env:
   OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
   APP_PORT: ""
-  # Set the kube context's namespace after login
-  OPENSHIFT_NAMESPACE: ${{ github.event.release.prerelease && secrets.OPENSHIFT_DEVELOPMENT_NAMESPACE || secrets.OPENSHIFT_PRODUCTION_NAMESPACE }}
   # Registries such as GHCR, Quay.io, and Docker Hub are supported.
   IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
   IMAGE_REGISTRY_USER: ${{ github.actor }}
@@ -45,12 +43,6 @@ jobs:
       - name: Install yarn packages
         run: yarn install
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -76,21 +68,85 @@ jobs:
 
       - name: Build and push
         uses: redhat-actions/buildah-build@v2
-        id: build-image
+        id: build-image-dev
+        if: "github.event.release.prerelease"
         with:
           context: apps/${{ matrix.app }}
           dockerfiles: |
             ./apps/${{ matrix.app }}/Dockerfile
           image: ${{ matrix.app }}
-          tags: ${{ github.event.release.prerelease && 'development' || 'latest' }} ${{ github.sha }}
+          tags: 'development' ${{ github.sha }}
 
       # https://github.com/redhat-actions/push-to-registry#readme
       - name: Push to registry
-        id: push-image
+        id: push-image-dev
         uses: redhat-actions/push-to-registry@v2
+        if: "github.event.release.prerelease"
         with:
-          image: ${{ steps.build-image.outputs.image }}
-          tags: ${{ steps.build-image.outputs.tags }}
+          image: ${{ steps.build-image-dev.outputs.image }}
+          tags: ${{ steps.build-image-dev.outputs.tags }}
           registry: ${{ env.IMAGE_REGISTRY }}
           username: ${{ env.IMAGE_REGISTRY_USER }}
           password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
+
+      - name: Build and push
+        uses: redhat-actions/buildah-build@v2
+        id: build-image-prod
+        if: "!github.event.release.prerelease"
+        with:
+          context: apps/${{ matrix.app }}
+          dockerfiles: |
+            ./apps/${{ matrix.app }}/Dockerfile
+          image: ${{ matrix.app }}
+          tags: 'latest' ${{ github.sha }}
+
+      # https://github.com/redhat-actions/push-to-registry#readme
+      - name: Push to registry
+        if: "!github.event.release.prerelease"
+        id: push-image-prod
+        uses: redhat-actions/push-to-registry@v2
+        with:
+          image: ${{ steps.build-image-prod.outputs.image }}
+          tags: ${{ steps.build-image-prod.outputs.tags }}
+          registry: ${{ env.IMAGE_REGISTRY }}
+          username: ${{ env.IMAGE_REGISTRY_USER }}
+          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
+
+      - name: Install oc
+        uses: redhat-actions/openshift-tools-installer@v1
+        with:
+          oc: 4
+
+      # https://github.com/redhat-actions/oc-login#readme
+      - name: Log in to OpenShift
+        uses: redhat-actions/oc-login@v1
+        if: "github.event.release.prerelease"
+        with:
+          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.OPENSHIFT_NAMESPACE_DEVELOPMENT }}
+
+      # This step should create a deployment, service, and route to run your app and expose it to the internet.
+      # https://github.com/redhat-actions/oc-new-app#readme
+      - name: Create and expose app
+        id: deploy-and-expose-dev
+        uses: redhat-actions/oc-new-app@v1
+        if: "github.event.release.prerelease"
+        with:
+          app_name: ${{ matrix.app }}-dev
+          image: ${{ steps.push-image-dev.outputs.registry-path }}
+          namespace: ${{ env.OPENSHIFT_NAMESPACE_DEVELOPMENT }}
+          port: ${{ env.APP_PORT }}
+
+      - name: Print application URL
+        if: "github.event.release.prerelease"
+        env:
+          ROUTE: ${{ steps.deploy-and-expose-dev.outputs.route }}
+          SELECTOR: ${{ steps.deploy-and-expose-dev.outputs.selector }}
+        run: |
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo
+          echo "======================== Your application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
